# -*- coding: utf-8 -*-
"""Technical Test-QA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pl2R_0MkZ-czm0uB0NlWTg6EuxnvLBHD
"""

import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

class TestDashboard(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        options = webdriver.ChromeOptions()
        options.add_argument("--headless")  # Operasikan tanpa tampilan GUI
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        cls.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
        cls.driver.get("https://pettycash.kalbenutritionals.web.id/")

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    # Test Login
    def test_login(self):
        driver = self.driver
        driver.find_element(By.NAME, "username").send_keys("michael.leonard")
        driver.find_element(By.NAME, "password").send_keys("abc")
        driver.find_element(By.XPATH, "//button[@type='submit']").click()
        time.sleep(3)
        self.assertIn("Dashboard", driver.title)

    # Test Fitur Master -> Department
    def test_master_department(self):
        driver = self.driver
        driver.find_element(By.XPATH, "//a[text()='Master']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='Department']").click()
        time.sleep(2)
        self.assertTrue(driver.find_element(By.XPATH, "//h1[contains(text(),'Department')]").is_displayed())

    # Test Fitur Transaction -> Kasbon
    def test_transaction_kasbon(self):
        driver = self.driver
        driver.find_element(By.XPATH, "//a[text()='Transaction']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='Kasbon']").click()
        time.sleep(2)
        self.assertTrue(driver.find_element(By.XPATH, "//h1[contains(text(),'Kasbon')]").is_displayed())

    # Test Fitur Report -> Bulanan
    def test_report_bulanan(self):
        driver = self.driver
        driver.find_element(By.XPATH, "//a[text()='Report']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='Bulanan']").click()
        time.sleep(2)
        self.assertTrue(driver.find_element(By.XPATH, "//h1[contains(text(),'Laporan Bulanan')]").is_displayed())

    # Test Fitur Approval -> Approval Kasbon
    def test_approval_kasbon(self):
        driver = self.driver
        driver.find_element(By.XPATH, "//a[text()='Approval']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='Approval Kasbon']").click()
        time.sleep(2)
        self.assertTrue(driver.find_element(By.XPATH, "//h1[contains(text(),'Approval Kasbon')]").is_displayed())

    # Test Navigasi Tidak Ditemukan -> User Tidak Ada
    def test_user_not_found(self):
        driver = self.driver
        driver.find_element(By.XPATH, "//a[text()='Master']").click()
        time.sleep(2)
        driver.find_element(By.XPATH, "//a[text()='User']").click()
        time.sleep(2)
        self.assertRaises(Exception, driver.find_element, By.XPATH, "//h1[contains(text(),'User')]")

if __name__ == "__main__":
    unittest.main()